name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Instalar Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose
    - name: Build backend service
      run: docker-compose -f PupShops/docker-compose.yml build backend

    - name: Build frontend service
      run: docker-compose -f PupShops/docker-compose.yml build frontend
