name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Instalar Docker Buildx para el build multi-plataforma
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Verificar la instalación de Docker Compose
    - name: Check Docker Compose version
      run: docker-compose --version

    # Construir el servicio backend
    - name: Build backend service
      run: |
        docker-compose -f docker-compose.yml build backend
        docker-compose -f docker-compose.yml up -d backend

    # Construir el servicio frontend
    - name: Build frontend service
      run: |
        docker-compose -f docker-compose.yml build frontend
        docker-compose -f docker-compose.yml up -d frontend

    # Listar los contenedores en ejecución después del build
    - name: List running containers
      run: docker ps

    # Ver los logs del servicio backend (agregar si necesitas revisar los logs)
    - name: Backend service logs
      run: docker-compose -f docker-compose.yml logs backend

    # Ver los logs del servicio frontend (agregar si necesitas revisar los logs)
    - name: Frontend service logs
      run: docker-compose -f docker-compose.yml logs frontend
