name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
      - deploy

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    # Verificar que docker-compose.yml existe en la ubicación correcta
    - name: Check for docker-compose.yml
      run: ls -la
      working-directory: ./PupShops # Ajusta esto si el archivo docker-compose.yml está en otro lugar

    # Instalar Docker Buildx para el build multi-plataforma
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Instalar Docker Compose
    - name: Install Docker Compose
      run: |
        sudo apt-get update
        sudo apt-get install -y docker-compose

    # Verificar la instalación de Docker Compose
    - name: Check Docker Compose version
      run: docker-compose --version

    # Verificar contenido del archivo docker-compose.yml
    - name: Show docker-compose.yml content
      run: cat docker-compose.yml
      working-directory: ./PupShops # Ajusta esto si el archivo docker-compose.yml está en otro lugar

    # Construir el servicio backend
    - name: Build backend service
      run: |
        docker-compose -f docker-compose.yml build backend
        docker-compose -f docker-compose.yml up -d backend
      working-directory: ./PupShops # Ajusta esto si el archivo docker-compose.yml está en otro lugar

    # Construir el servicio frontend
    - name: Build frontend service
      run: |
        docker-compose -f docker-compose.yml build frontend
        docker-compose -f docker-compose.yml up -d frontend
      working-directory: ./PupShops # Ajusta esto si el archivo docker-compose.yml está en otro lugar

    # Listar los contenedores en ejecución después del build
    - name: List running containers
      run: docker ps
