name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v2

      # 2. Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      # 3. Install Docker Compose
      - name: Install Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install docker-compose -y

      # 4. List files to verify docker-compose.yml exists
      - name: List files
        run: ls -R

      # 5. Deploy with Docker Compose (ajusta la ruta si es necesario)
      - name: Deploy with Docker Compose
        run: |
          docker-compose -f ./PupShops/docker-compose.yml up --build -d
