name: Deploy to Render

on:
  push:
    branches:
      - main  # Cambia esta rama si deseas usar otra rama para los despliegues

jobs:
  deploy:
    name: Build and Deploy to Render
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      # Configura el acceso a Docker
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Construye la imagen Docker
      - name: Build Docker image
        run: |
          docker build -t fmonfasani/pupshops:latest .

      # Empuja la imagen Docker a Docker Hub
      - name: Push Docker image
        run: |
          docker push fmonfasani/pupshops:latest

      # Loguea en Render
      - name: Log in to Render
        run: |
          render login --api-key ${{ secrets.RENDER_API_KEY }}

      # Desplegar en Render
      - name: Deploy to Render
        run: |
          render deploy service srv-crrap656l47c73cgehig --api-key ${{ secrets.RENDER_API_KEY }} --branch main
