name: CI/CD Pipeline

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}  # Define estas credenciales en los Secrets de GitHub
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image for frontend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-frontend:latest ./front
          docker push ${{ secrets.DOCKER_USERNAME }}/app-frontend:latest

      - name: Build and push Docker image for backend
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/app-backend:latest ./back/pupshops
          docker push ${{ secrets.DOCKER_USERNAME }}/app-backend:latest

      - name: Deploy to Render
        run: |
          curl -X POST -H "Authorization: Bearer ${{ secrets.RENDER_API_KEY }}" \
            https://api.render.com/v1/services/YOUR_RENDER_SERVICE_ID/deploys
